### ISSUE TITLE
SDK test issue

### ISSUE THREAD

**Issue by sherwinski** [heyitsbryanm/first-git#12]
Hey I'm having an issue with [this library](https://github.com/imgix/imgix-core-js). Can you please fix this bug reported here?

```js
const num = 1;
assert.equal(num + num, 2);
``` 

Thanks for the help 👍 😁 🙃

**Comment by sherwinski** [comment]
Here's a follow up comment in the thread

**Comment by heyitsbryanm** [comment]
Testing a follow-up comment

**Comment by heyitsbryanm** [comment]
Testing again

**Comment by heyitsbryanm** [comment]
Alright yo let's another test
